### ISSUE TITLE
Repo release tag

### ISSUE THREAD

**Issue by TheNotTooDistantFuture** [cxcloud/helm-fluentd-kinesis-firehose#4]
Hello,

Could the author tag the repo with the release version? We'd like to reference it from our helm charts.

Thanks!
Aidan

**Comment by jarl-tornroos** [comment]
Hi,

Nice that you like the helm chart.

I created the release tag v0.1.0

Jarl

**Comment by TheNotTooDistantFuture** [comment]
Thanks!
